### ISSUE TITLE
FileNotFoundError uploading XML file running as systemd service

### ISSUE THREAD

**Issue by daviessm** [portagefilelist/client#11]
Mar 09 10:53:10 bang pfl[2528120]: working on (740 of 740) app-emulation/qemu-5.2.0-r1
    Mar 09 10:53:10 bang pfl[2528120]: uploading xml file /tmp/pfltw3e1bfm.xml.bz2 to https://upload.portagefilelist.de/data.php ...
    Mar 09 10:53:10 bang pfl[2528120]: Traceback (most recent call last):
    Mar 09 10:53:10 bang pfl[2528120]:   File "/usr/lib/python-exec/python3.8/pfl", line 10, in <module>
    Mar 09 10:53:10 bang pfl[2528120]:     sys.exit(main())
    Mar 09 10:53:10 bang pfl[2528120]:   File "/usr/lib/python-exec/python3.8/pfl", line 7, in main
    Mar 09 10:53:10 bang pfl[2528120]:     pfl.pfl.PFL().run()
    Mar 09 10:53:10 bang pfl[2528120]:   File "/usr/lib/python3.8/site-packages/pfl/pfl.py", line 227, in run
    Mar 09 10:53:10 bang pfl[2528120]:     self._finish(xmlfile, True)
    Mar 09 10:53:10 bang pfl[2528120]:   File "/usr/lib/python3.8/site-packages/pfl/pfl.py", line 174, in _finish
    Mar 09 10:53:10 bang pfl[2528120]:     hconfig = open(INFOFILE, 'w')
    Mar 09 10:53:10 bang pfl[2528120]: FileNotFoundError: [Errno 2] No such file or directory: 'None/.pfl.info'
    Mar 09 10:53:10 bang systemd[1]: pfl.service: Main process exited, code=exited, status=1/FAILURE
    Mar 09 10:53:10 bang systemd[1]: pfl.service: Failed with result 'exit-code'.
    Mar 09 10:53:10 bang systemd[1]: Failed to start Portage File List upload.
    Mar 09 10:53:10 bang systemd[1]: pfl.service: Consumed 20.413s CPU time.

Using `pfl-3.1-r1` from Portage and Python 3.8.

**Comment by daviessm** [comment]
Looks like this is #10.

**Comment by tuxmainy** [comment]
Hi,
yes, this is #10 which I merged. The PFL script should run as user "portage" which then would result in using "/var/lib/pfl/pfl.info"

Thanks
Daniel
