### ISSUE TITLE
Allow uploading data for single (rather than all) packages (in build server context)?

### ISSUE THREAD

**Issue by hartwork** [portagefilelist/client#13]
Hi!

I have a build server that builds ebuilds as they appear in Gentoo. I consider integrating an upload to portagefilelist.de but it seems wasteful to upload data for all packages after every single build. If that kind of data is of interest to have to you, it would be great to have a mode to collect data for just one single package. What do you think?

Best, Sebastian

**Comment by tuxmainy** [comment]
Hi,
PFL should only upload builds which are newer than "last run"-timestamp. This is the primary idea behind /var/lib/pfl/pfl.info or $HOME/.pfl.info . So as long as you do not remove this file between the builds PFL should only upload diffs?!

regards
Daniel

**Comment by hartwork** [comment]
Hi @tuxmainy, in my environment — context is https://github.com/hartwork/binary-gentoo — there is no info from a previous run because every build starts from the same state docker image so it would always be the first run.

**Comment by tuxmainy** [comment]
So adding an argument to the pfl call like 'pfl net-misc/bridge-utils-1.6' would be an option? That way one must use CPV and not CP.

**Comment by hartwork** [comment]
That would totally work for me, I guess, yes!

**Comment by hartwork** [comment]
@tuxmainy any news?

**Comment by bananas-repos** [comment]
Dusting old issues here.

After I get the hang of the e-file I will look into it.

**Comment by bananas-repos** [comment]
@hartwork In the upcomming release, there will be a option to provide a package atom. It will only collect the data of the provided package and upload it.

**Comment by hartwork** [comment]
@bananas-repos cool!

**Comment by bananas-repos** [comment]
Build a release. Will take some time to be in the portage tree.
