### ISSUE TITLE
Publishing database dumps for offline searching

### ISSUE THREAD

**Issue by sijanec** [portagefilelist/client#16]
Hello! This is not really an issue, but more of an improvement.

It would be useful to be able to download database dumps from the collection infrastructure. This would enable offline searches of packages - maybe something like Debian's command-not-found could be implemented in the future. Apart from that, some sort of machine analysis of packages could be easier and would not require HTML scraping and putting load on your server.

Thanks for reading, what do you think?

P. S.: Perhaps database dumps are already being published and I did not find them, if that's the case, can you please direct me to the download method?

**Comment by bananas-repos** [comment]
Dusting old issues.

Just creating a SQL dump could be done. But using it locally, you would need the DB Server and the server files to query the DB. Also the e-file should be routed to the local install.

So it is not so easy done as said.

**Comment by sijanec** [comment]
I'd be really happy with a SQL dump if that's possible.

**Comment by bananas-repos** [comment]
With the current service setup I'm not able to automate the DB dump.

Here is a current one:  https://www.portagefilelist.de/db-dump_20230718.sql.gz

**Comment by sijanec** [comment]
Thank you!

2023-07-18 10:49 GMT+02.00, Banana ***@***.***>:
