### ISSUE TITLE
Add a flag to show exactly what information is sent.

### ISSUE THREAD

**Issue by Sneethe** [portagefilelist/client#33]
I see no reason not to include a way for the privacy conscious Gentoo user to actually see what information is going to be sent the next time pfl is run. 
Perhaps to follow emerge cmd continuity, --pretend, -p could be used.

**Comment by bananas-repos** [comment]
Hello and thank you four your feedback.

As a first action I've updated the Wiki and added a new section about the collected data: https://wiki.gentoo.org/wiki/Pfl#Data_policy

As for the pretend option, I will look into it.

**Comment by bananas-repos** [comment]
Added a pretend option with https://github.com/portagefilelist/client/commit/e097d438a3872662b77aec6a81a1b591910f37b3

**Comment by Sneethe** [comment]
This is excellent. Thank you.
