### ISSUE TITLE
Website | Mention that portagefilelist is only for official Gentoo repo.

### ISSUE THREAD

**Issue by Sneethe** [portagefilelist/client#34]
I didn't anywhere on the website or wiki page what the scope of pfl is in regards to repo ebuild tracking.

Perhaps relevant https://github.com/portagefilelist/client/issues/20

**Comment by bananas-repos** [comment]
Hello and thank you for your feedback and recommendations for improvement.

I've added a new section in the wiki about that: https://wiki.gentoo.org/wiki/Pfl#Scanned_repositories

Does this suffice?
