### ISSUE TITLE
Scan binary packages from bin cache too?

### ISSUE THREAD

**Issue by APN-Pucky** [portagefilelist/client#35]
I have a large cache of accumulated binpkgs. Does pfl scan them too? Is it something that would be valuable?

**Comment by bananas-repos** [comment]
Hello.

As far as I can tell and understand, since I do not use bin packages https://wiki.gentoo.org/wiki/Binary_package_guide, pfl does include those files instaled by bin packags since they should be also "registered" by the usual emerge process.
