### ISSUE TITLE
GPL-2 (without the "or later" clause) to GPL-3 update

### ISSUE THREAD

**Issue by parona-source** [portagefilelist/client#39]
The apparent GPL-2 license of the repository didn't have the "or later" clause meaning you can't just update the license to GPL-3.

Updating the license would require the permission of the previous contributors.

**Comment by bananas-repos** [comment]
Thx for the hint. I'm not that fluent in licensing and was in the impression that there is no harm done.
Gonna fix this.

**Comment by bananas-repos** [comment]
Done
