### ISSUE TITLE
Create info file

### ISSUE THREAD

**Issue by bananas-repos** [portagefilelist/client#44]
There is already man file for e-file and pfl. The generated man file does mention the info command. info e-file or info pfl does work but does not list any more information.

Either create info files with more information or remove the "The full documentation for is maintained as a Texinfo manual.  If the ..." notice

**Comment by parona-source** [comment]
You can disable the info notice in help2man with -N/--no-info

**Comment by bananas-repos** [comment]
Fixed with [95b64a8](https://github.com/portagefilelist/client/commit/95b64a804634133c0c04b4b8bc185c6e381e2b72)
