### ISSUE TITLE
Some files trigger "TypeError: sequence item 0: expected str instance, NoneType found" in e-file

### ISSUE THREAD

**Issue by parona-source** [portagefilelist/client#46]
```
 $ e-file Address.pm
 *  None/None
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/e-file", line 97, in <module>
    sys.stdout.write(colored('        Seen Versions:          %s\n' % ' '.join(versions), 'green'))
                                                                      ^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
 $ e-file --version
e-file 3.4
```

I haven't found the common culprit. Address.pm is where I discovered this which does have packages associated with it https://www.portagefilelist.de/?fs=Address.pm#panchor.

A list that I've tried:
* Address.pm -> fail
* clang.conf -> fail
* clang -> success
* gentoo-common.cfg -> success
* pfl.py -> success

**Comment by bananas-repos** [comment]
I do supect an upsie I did some days ago while importing.

I still have a problem with uploads from systems which have "everything" installed. Like not everything but at least 10 gentoo-sources packages. Kernel sources are huge...

**Comment by bananas-repos** [comment]
Data inconsistency is fixed. 

Address.pm -> success
clang.conf -> success
clang -> success
gentoo-common.cfg -> success
pfl.py -> success

And invalid lines without any category and package information in the web view (https://www.portagefilelist.de/?fs=Address.pm#panchor) are gone, too.
