### ISSUE TITLE
e-file is missing space

### ISSUE THREAD

**Issue by henri-gasc** [portagefilelist/client#54]
I think it should be only a minor change to do, but when using `e-file`, the 'Portage versions' line do not have space separating the versions.  
Example:
```bash
$ e-file 'IexBaseExc.h'               
[I]  media-libs/openexr
	Seen Versions:       3.1.11 3.1.12 3.1.7 3.2.2
	Portage Versions:    3.1.113.1.123.1.5-r13.1.73.2.2
...
```
By the way, the versions appear to not be sorted / not sorted correctly, I don't know if you want to "fix" it.

**Comment by bananas-repos** [comment]
Thank you. I was kind of fixed already with https://github.com/portagefilelist/client/pull/53, but another error came up.
I've also sorted the versions now.

Thank you for your time and input!

It will be fixed with an upcoming version/release.

**Comment by henri-gasc** [comment]
No problem, happy to help
