### ISSUE TITLE
e-file should handle files on a /usr merge system properly

### ISSUE THREAD

**Issue by jonasstein** [portagefilelist/client#55]
How to reproduce on a /usr merge system:

```
ls -al /usr/bin/ip
-rwxr-xr-x 1 root root 685760 Jan  1 18:02 /usr/bin/ip

e-file  /usr/bin/ip
SEARCH_FAILED
Invalid search criteria or nothing found. Either use a filename or complete path. Use * as a wildcard. Also check the path of the file. If the packagename is present the file is not recorded.
Something went wrong with the request result.

e-file /bin/ip
[I]  sys-apps/iproute2
	Seen Versions:       5.4.0 6.3.0 6.4.0 6.5.0 6.6.0 6.6.0-r1 6.6.0-r2 6.6.0-r3 9999
	Portage Versions:    6.6.06.6.0-r16.6.0-r39999
	Repository:          gentoo
	Installed Versions:  6.6.0-r3(Mon Jan  1 18:02:43 2024) 
	Homepage:            https://wiki.linuxfoundation.org/networking/iproute2
	Description:         kernel routing and traffic control utilities
	Matched Files:       /bin/ip

```

`e-file  /usr/bin/ip` should find a match.

**Comment by bananas-repos** [comment]
Hello and thank you for your time and feedback.

https://wiki.gentoo.org/wiki/Merge-usr

>  This is often referred to as the "/usr merge" where the /bin, /sbin, /lib, and /lib64 are permanently migrated to the /usr/bin, /usr/sbin, /usr/lib and /usr/lib64 directories respectively. As part of the migration, the former non-/usr directories will then be replaced with symlinks pointing to the new locations for backwards compatibility. 

```
lrwxrwxrwx   1 root root    7 Jan  7 10:29 bin -> usr/bin
drwxr-xr-x   2 root root 4096 Nov 28  2019 boot
drwxr-xr-x  16 root root 3860 Mar 18 19:16 dev
drwxr-xr-x  63 root root 4096 Mar 18 19:16 etc
drwxr-xr-x   3 root root 4096 Dec  1  2019 home
lrwxrwxrwx   1 root root    7 Jan  7 10:29 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Jan  7 10:29 lib64 -> usr/lib64
```

So, `/bin/ip` is the same as `/usr/sbin/ip` and it looks like `sys-apps/iproute2` does install it files into `/bin/`. This path is recorded (I'm note sure how) and read by e-file. e-file or pfl does only know what portage/emerge knows or records. There is currently now way how pfl/e-file would also recognize this path for this package.

See the created xml from pfl for `sys-apps/iproute2`
[pfl-re2334nb.xml.txt](https://github.com/portagefilelist/client/files/14641059/pfl-re2334nb.xml.txt)

**Comment by bananas-repos** [comment]
I've implemented some logic to handle this topic. It effects the website search and e-file.

search for /usr/bin/ip: https://www.portagefilelist.de/?fs=%2Fusr%2Fbin%2Fip#panchor
search for /bin/ip: https://www.portagefilelist.de/?fs=%2Fbin%2Fip#panchor
